# coding: utf-8

"""
    Cokomo Public Api

    Public API Documentation for Cokomo system

    The version of the OpenAPI document: v1
    Contact: cokomo-team@haw-hamburg.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cokomo.api.learning_goal_api import LearningGoalApi  # noqa: E501


class TestLearningGoalApi(unittest.TestCase):
    """LearningGoalApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LearningGoalApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_learning_goal_id_details_get(self) -> None:
        """Test case for learning_goal_id_details_get

        """
        pass

    def test_learning_goal_id_get(self) -> None:
        """Test case for learning_goal_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
