# coding: utf-8

"""
    Cokomo Public Api

    Public API Documentation for Cokomo system

    The version of the OpenAPI document: v1
    Contact: cokomo-team@haw-hamburg.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cokomo.api.metamodel_api import MetamodelApi  # noqa: E501


class TestMetamodelApi(unittest.TestCase):
    """MetamodelApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetamodelApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_metamodel_get(self) -> None:
        """Test case for metamodel_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
