# coding: utf-8

"""
    Cokomo Public Api

    Public API Documentation for Cokomo system

    The version of the OpenAPI document: v1
    Contact: cokomo-team@haw-hamburg.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cokomo.api.competence_base_api import CompetenceBaseApi  # noqa: E501


class TestCompetenceBaseApi(unittest.TestCase):
    """CompetenceBaseApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CompetenceBaseApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_competence_base_id_details_get(self) -> None:
        """Test case for competence_base_id_details_get

        """
        pass

    def test_competence_base_id_get(self) -> None:
        """Test case for competence_base_id_get

        """
        pass

    def test_competence_base_id_neighbours_get(self) -> None:
        """Test case for competence_base_id_neighbours_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
