# coding: utf-8

# flake8: noqa
"""
    Cokomo Public Api

    ## 👉 [Please see the CoKoMo documentation for more information.](https://cokomo-it.de/docs/start/api/documentation/)

    The version of the OpenAPI document: v1
    Contact: cokomo-team@haw-hamburg.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from cokomo.models.competence_base import CompetenceBase
from cokomo.models.competence_base_type import CompetenceBaseType
from cokomo.models.competence_level import CompetenceLevel
from cokomo.models.edge_type import EdgeType
from cokomo.models.learning_goal import LearningGoal
from cokomo.models.metamodel import Metamodel
from cokomo.models.neighbour import Neighbour
from cokomo.models.neighbour_edge import NeighbourEdge
