# coding: utf-8

"""
    Cokomo Public Api

    ## 👉 [Please see the CoKoMo documentation for more information.](https://cokomo-it.de/docs/start/api/documentation/)

    The version of the OpenAPI document: v1
    Contact: cokomo-team@haw-hamburg.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist
from cokomo.models.neighbour_edge import NeighbourEdge

class Neighbour(BaseModel):
    """
    Neighbour
    """
    id: Optional[StrictStr] = None
    title: Optional[StrictStr] = None
    short_description: Optional[StrictStr] = Field(None, alias="shortDescription")
    type: Optional[StrictStr] = None
    relation: Optional[NeighbourEdge] = None
    neighbours: Optional[conlist(Neighbour)] = None
    __properties = ["id", "title", "shortDescription", "type", "relation", "neighbours"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Neighbour:
        """Create an instance of Neighbour from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of relation
        if self.relation:
            _dict['relation'] = self.relation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in neighbours (list)
        _items = []
        if self.neighbours:
            for _item in self.neighbours:
                if _item:
                    _items.append(_item.to_dict())
            _dict['neighbours'] = _items
        # set to None if id (nullable) is None
        # and __fields_set__ contains the field
        if self.id is None and "id" in self.__fields_set__:
            _dict['id'] = None

        # set to None if title (nullable) is None
        # and __fields_set__ contains the field
        if self.title is None and "title" in self.__fields_set__:
            _dict['title'] = None

        # set to None if short_description (nullable) is None
        # and __fields_set__ contains the field
        if self.short_description is None and "short_description" in self.__fields_set__:
            _dict['shortDescription'] = None

        # set to None if type (nullable) is None
        # and __fields_set__ contains the field
        if self.type is None and "type" in self.__fields_set__:
            _dict['type'] = None

        # set to None if neighbours (nullable) is None
        # and __fields_set__ contains the field
        if self.neighbours is None and "neighbours" in self.__fields_set__:
            _dict['neighbours'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Neighbour:
        """Create an instance of Neighbour from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Neighbour.parse_obj(obj)

        _obj = Neighbour.parse_obj({
            "id": obj.get("id"),
            "title": obj.get("title"),
            "short_description": obj.get("shortDescription"),
            "type": obj.get("type"),
            "relation": NeighbourEdge.from_dict(obj.get("relation")) if obj.get("relation") is not None else None,
            "neighbours": [Neighbour.from_dict(_item) for _item in obj.get("neighbours")] if obj.get("neighbours") is not None else None
        })
        return _obj

Neighbour.update_forward_refs()

