# coding: utf-8

# flake8: noqa

"""
    Cokomo Public Api

    ## 👉 [Please see the CoKoMo documentation for more information.](https://cokomo-it.de/docs/start/api/documentation/)

    The version of the OpenAPI document: v1
    Contact: cokomo-team@haw-hamburg.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from cokomo.api.competence_base_api import CompetenceBaseApi
from cokomo.api.learning_goal_api import LearningGoalApi
from cokomo.api.metamodel_api import MetamodelApi

# import ApiClient
from cokomo.api_response import ApiResponse
from cokomo.api_client import ApiClient
from cokomo.configuration import Configuration
from cokomo.exceptions import OpenApiException
from cokomo.exceptions import ApiTypeError
from cokomo.exceptions import ApiValueError
from cokomo.exceptions import ApiKeyError
from cokomo.exceptions import ApiAttributeError
from cokomo.exceptions import ApiException

# import models into sdk package
from cokomo.models.competence_base import CompetenceBase
from cokomo.models.competence_base_type import CompetenceBaseType
from cokomo.models.competence_level import CompetenceLevel
from cokomo.models.edge_type import EdgeType
from cokomo.models.learning_goal import LearningGoal
from cokomo.models.metamodel import Metamodel
from cokomo.models.neighbour import Neighbour
from cokomo.models.neighbour_edge import NeighbourEdge
